### ISSUE TITLE
Rainmeter interface has stop to working

### ISSUE THREAD

**Issue by Kimary94** [infeeeee/kimai-cmd#2]
Hello, me again.

I don't know why but the rainmeter part stop to working :(
It won't to refresh anymore, if i use kimai-cmd it work properly, it start and stop a task, it give the list of project but the rainmeter interface doesn't start or stop any project and doesn't refresh if I change the current project via browser

Any idea about the problem? Maybe the subfolder option give problems to the core?

Thanks

**Comment by infeeeee** [comment]
It freezed once or twice on my PC as well, but when I restarted rainmeter everything went back to normal, and I couldn't replicate the problem, so I couldn't solve it.

If it happens to you more regularly, I would like to help you but, need more information, what's going wrong.
If you can use the cmd than it's definitely a problem with the rainmeter.

Enable logging in the skin this way
Rightclick on the skin - edit skin
Find the `[MeasureReload]` section
Copy the following at the end of the section:
```
OutputFile=#CURRENTPATH#kimai-cmd\log.txt
OutputType=UTF8
```
Save, then refresh the skin.

It will create a log.txt next to the cmd, copy the contents after it's freezes.

Other things to try:

If you click on the reload button on the widget what happens? it should disappear for a second. it's possible that it's so quick that you cant see it, that's the normal behaviour.  When it starts the command it disappears, when there an answer got from the server it appears again. Does it remain hidden?

Rightclick on the rainmeter icon on taskbar - refresh all

Delete the kimaiData.inc and kimaiVars.inc files next to the kimai-cmd.exe, than reload button. they are created every time you click reload

**Comment by Kimary94** [comment]
On this days I'm using another pc at home, I will know you if something happen even on this pc

**Comment by Kimary94** [comment]
I'm back,
I've partially resolve the problem deleting and and recreating .inc files but it seems like kimai-cmd don't work well with rainmeter, if i use it from prompt everything work well but if i try to use directly rainmeter nothing happen on the server side, even if i use refresh button nothing happen.
The log file stay blank.

Sorry for open the issue in kimai-cmd, maybe I've to reopen it in rainmeter interface's git.

**Comment by infeeeee** [comment]
I created a new release, you can download it from [here](https://github.com/infeeeee/kimai-widget/releases/tag/0.0.5)

Please delete the previous version totally, so before installing this delete your kimai-widget folder from Documents\Rainmeter, let's start it clean.

After install edit settings.ini, load the skin, rainmeter on taskbar->right click->refresh all, and click on the reload button it should create a log.txt.

I changed kimai-cmd so it's deletes and recreates the rainmeter files instead of overwriting them, maybe it's solves your issue

Other thing you can try is disable all other rainmeter skins, maybe one of them overlays the button invisibly, so you can't click on that.

You can enable logging in rainmeter on taskbar-> logging -> start logging, click on the buttons, than open the log file, and look for something suspicious

**Comment by infeeeee** [comment]
Ok, I think we solved this issue, so I close it. If the problem appears again, I will open it. 

And after all it was a bug in kimai-cmd, not in the rainmeter interface, so you started the issue on the right project accidentally :)
